In [2]:
import numpy as np

In [3]:
# check version of numpy
np.__version__

'1.26.3'

# Array

In [4]:
x = np.array([10,20,30,40]) # 1D Array (1[])
x

array([10, 20, 30, 40])

In [5]:
x.ndim #property of numpy (without ())

1

In [6]:
y = np.array([[10,20],[30,40]]) #2d Array(2[])
y

array([[10, 20],
       [30, 40]])

In [8]:
y.ndim

2

In [9]:
z = np.array([[[10,20],[30,40],[50,60]]]) #3d Array (3[])
z

array([[[10, 20],
        [30, 40],
        [50, 60]]])

In [10]:
z.ndim

3

In [12]:
z.shape #in 3D (block,row,columns)

(1, 3, 2)

In [18]:
y

array([[10, 20],
       [30, 40]])

In [14]:
y.shape #in 2D (row,shape)

(2, 2)

In [16]:
x

array([10, 20, 30, 40])

In [20]:
x.shape #in 1D element present in array

(4,)

# Create Numpy Array

In [22]:
data = np.arange(11) #same as python range method 11 is excluding
data #1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
num = np.arange(2,20)
num

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [25]:
num1 = np.arange(2,101,2) #(start,stop(exclude),step)
num1

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [30]:
num2 = np.arange(100,1,-2)
num2

array([100,  98,  96,  94,  92,  90,  88,  86,  84,  82,  80,  78,  76,
        74,  72,  70,  68,  66,  64,  62,  60,  58,  56,  54,  52,  50,
        48,  46,  44,  42,  40,  38,  36,  34,  32,  30,  28,  26,  24,
        22,  20,  18,  16,  14,  12,  10,   8,   6,   4,   2])

In [31]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
data[0] #support indixing

0

In [33]:
data[-1]

10

In [34]:
data.shape

(11,)

In [35]:
data[1:5] #supporting slicing

array([1, 2, 3, 4])

In [42]:
# array with constant value
#np.full(shape,fill_value)
# shape means row and columns, it may b 1D as well
#Return random floats in the half-open interval (0.0, 1.0)
npf = np.full((4,4),10) #(4 rows,4 column) and 1 as a constant value
npf

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [43]:
np.random.random(5)

array([0.14215206, 0.82190177, 0.90199369, 0.35195449, 0.29354744])

In [44]:
np.random.random((4,5)) # 2D (4row,5columns)

array([[0.83748943, 0.73264217, 0.58824514, 0.07026739, 0.46989652],
       [0.60353023, 0.08263862, 0.60888681, 0.75926601, 0.71633172],
       [0.71333843, 0.41237378, 0.34987773, 0.2898756 , 0.72767618],
       [0.6665123 , 0.50190644, 0.76571852, 0.47647165, 0.09613779]])

In [45]:
np.random.random(((2,3,3))) #3D (2block,3row,3columns)

array([[[0.94756129, 0.37832526, 0.48826988],
        [0.60471513, 0.30292123, 0.12770782],
        [0.89293497, 0.98138705, 0.62548116]],

       [[0.31713164, 0.26997473, 0.06922807],
        [0.70391565, 0.91775536, 0.20100291],
        [0.28814827, 0.25870043, 0.002358  ]]])

In [46]:
#randint(low,high,size)
#randint(low, high=None, size=None, dtype=int)
np.random.randint(1,11,15)

array([ 1,  7, 10,  6,  2,  8,  1,  3,  2,  9,  2,  5,  6,  8, 10])

In [50]:
np.random.randint(2,size=10) #(2high,size=10)

array([1, 1, 0, 1, 1, 0, 1, 0, 0, 0])

In [52]:
np.random.randint(5,size=10)

array([3, 1, 0, 4, 1, 3, 4, 4, 4, 1])

In [54]:
rn = np.random.randint(3,5,(3,4)) #(3low,5high,size=(3row,4colunm))
rn

array([[4, 4, 3, 3],
       [4, 3, 4, 3],
       [4, 4, 3, 3]])

In [55]:
rn[2:,2:] #slicing[row:column]
#[staring row:stop row,staring column:stop column]

array([[3, 3]])